### ISSUE TITLE
Checks Intermintent fail

### ISSUE THREAD

**Issue by alexwbaule** [sensu-plugins/sensu-plugins-windows#33]
Hi Guys, 

Im using All checks, and sometimes i got this error in the execution.

Output: Check failed to run: undefined method `split' for nil:NilClass, ["C:/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-windows-0.0.10/bin/check-windows-ram.rb:50:in `acquire_ram_usage'", "C:/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-windows-0.0.10/bin/check-windows-ram.rb:57:in `run'", "C:/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugin-1.4.4/lib/sensu-plugin/cli.rb:58:in `block in <class:CLI>'"]

Sometimes is check-windows-ram, sometimes is the check-windows-process

C:/opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `new': fail: OLE initialize (RuntimeError)
    HRESULT error code:0x80070583
      Class does not exist.
 from C:/opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
 from C:/opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
 from C:/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-windows-0.0.10/bin/check-windows-process.rb:30:in `<top (required)>'
 from C:/opt/sensu/embedded/bin/check-windows-process.rb:22:in `load'
 from C:/opt/sensu/embedded/bin/check-windows-process.rb:22:in `<main>'

The error appears, and 2 or 3 checks later back to normal.

**Comment by absolutejam** [comment]
I recall having the same issue a while back, but this is pre 1.0.

I'm going to add the whole lot of Windows checks in my env and see what results I get, to see if this is still an issue.

@alexwbaule are you still hitting these issues? Additionally, are you running the checks by explicitly specifying `ruby` or using the full path?

**Comment by alexwbaule** [comment]
Hi @absolutejam ,

Im using the full path, but i call de .bat file. Not the Ruby.

**Comment by danb223** [comment]
@absolutejam We have just started using this module and I am also seeing the issue in the latest version of the module, happening randomly, we are using the full path, I am seeing this fail on processor queue, cpu usage and ram usage checks
`split' for nil:NilClass, [\"c:/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-windows-2.4.0/bin/check-windows-ram.rb:47:in `acquire_ram_usage'\", \"c:/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-windows-2.4.0/bin/check-windows-ram.rb:54:in `run'\", \"c:/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugin-1.4.5/lib/sensu-plugin/cli.rb:58:in `block in <class:CLI>'\"]
ndefined method `split' for nil:NilClass, [\"c:/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-windows-2.4.0/bin/check-windows-processor-queue-length.rb:42:in `run'\", \"c:/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugin-1.4.5/lib/sensu-plugin/cli.rb:58:in `block in <class:CLI>'\"]

**Comment by danb223** [comment]
We have actually found out that ours appears to be tied to the same time the sensu agent restarts, which is caused by us putting a custom json file in sensu, which seems to be hitting a purge but see https://github.com/sensu/sensu-puppet/issues/879
